server:
  port: 6002
spring:
  application:
    name: eureka-client-demo
eureka:
  client:
    register-with-eureka: true #注册到Eureka的注册中心
    fetch-registry: true #获取注册实例列表
    service-url:
      defaultZone: http://localhost:6001/eureka/ #配置注册中心地址
